In [2]:
import json 
import pandas as pd 
import numpy as np
from ast import literal_eval

In [3]:
#import TS files
f1 = 'https://upday-data-assignment.s3.eu-west-1.amazonaws.com/lake/2019-02-15.tsv'
f2 = 'https://upday-data-assignment.s3.eu-west-1.amazonaws.com/lake/2019-02-16.tsv'
f3 = 'https://upday-data-assignment.s3.eu-west-1.amazonaws.com/lake/2019-02-17.tsv'

# Convert to dataframes
t1 = pd.read_csv(f1, sep='\t', header=0)
t2 = pd.read_csv(f1, sep='\t', header=0)
t3 = pd.read_csv(f1, sep='\t', header=0)

In [18]:
#Apped all files into 1
T = t1.append(t2.append(t3)).reset_index()

#Create a copy for test
T_1 = T.copy()

In [19]:
# replace nan values
T_1['ATTRIBUTES'] = T_1['ATTRIBUTES'].fillna('{}')
T_2 = T_1.copy()
T_1['ATTRIBUTES'] = T_1['ATTRIBUTES'].apply(json.loads)
T_1['ATTRIBUTES'] = T_1['ATTRIBUTES'].apply(lambda x: {} if pd.isna(x) else x)

In [20]:
## Get expected columns (keys) list
expected_cols = pd.json_normalize(T_1['ATTRIBUTES'][0]).columns.to_list()

In [39]:
# Flatten json and append columns to main DF
df_ATTRIBUTES = pd.json_normalize(T_1['ATTRIBUTES'])
complete_df = pd.concat([T_1, df_ATTRIBUTES], axis=1).drop('ATTRIBUTES', axis=1)

In [44]:
complete_df.head().to_csv('check.csv', index=False)

In [55]:
complete_df.EVENT_NAME.unique()

array(['my_news_card_viewed', 'top_news_card_viewed', 'article_closed',
       'article_viewed', 'content_shared', 'home_teaser_tapped',
       'bottom_navigation_bar_clicked', 'three_dot_menu_clicked',
       'feature_discovery_closed', 'refreshed_manually',
       'read_it_later_article_saved', 'deepdiving_icon_clicked',
       'search_closed', 'advertisement_clicked',
       'auto_onboarding_completed', 'feature_discovery_shown',
       'onboarding_aborted_navigated_away',
       'read_it_later_article_removed', 'categories_changed',
       'deepdiving_stream_selected', 'low_content_home_viewed',
       'application_error', 'content_liked',
       'notification_preferences_changed', 'onboarding_aborted_paused',
       'search_advertisement_viewed', 'feature_discovery_clicked',
       'read_it_later_article_opened', 'low_content_my_news_viewed',
       'source_blacklist_changed'], dtype=object)

In [42]:
complete_df.columns

Index(['index', 'TIMESTAMP', 'MD5(SESSION_ID)', 'EVENT_NAME', 'MD5(USER_ID)',
       'category', 'id', 'noteType', 'orientation', 'position', 'publishTime',
       'sourceDomain', 'sourceName', 'stream', 'streamType', 'subcategories',
       'title', 'url', 'browser', 'network', 'from', 'feature', 'Category',
       'ID', 'Note Type', 'Orientation', 'Position', 'Source', 'Source Id',
       'Stream Type', 'Title', 'Type', 'URL', 'format', 'provider', 'type',
       'navigatedTo', 'navigatedFrom', 'interesting', 'breakingNewsEnabled',
       'adType', 'rank', 'action'],
      dtype='object')

In [ ]:
complete_df

In [106]:
#prepare data for table article_performance 
stage = complete_df[['id', 'ID', 'TIMESTAMP', 'EVENT_NAME','title', 'category']][(complete_df.EVENT_NAME.str.contains("card")) | (complete_df.EVENT_NAME.str.contains("article"))].sort_values(by=['id']).reset_index(drop=True)

In [107]:
#limit the timestamp to only date part
stage['date'] = stage.TIMESTAMP.str[:10]

In [108]:
stage.head()

,id,ID,TIMESTAMP,EVENT_NAME,title,category,date
0,-1e_PWmoy-tnoBrgcDA2-A,NaN,2019-02-15 01:55:33.999 +0000,my_news_card_viewed,"Aktorzy, którzy zginęli na planie filmowym i p...",fashion_beauty_lifestyle,2019-02-15
1,-1e_PWmoy-tnoBrgcDA2-A,NaN,2019-02-15 01:55:33.999 +0000,my_news_card_viewed,"Aktorzy, którzy zginęli na planie filmowym i p...",fashion_beauty_lifestyle,2019-02-15
2,-1e_PWmoy-tnoBrgcDA2-A,NaN,2019-02-15 01:55:33.999 +0000,my_news_card_viewed,"Aktorzy, którzy zginęli na planie filmowym i p...",fashion_beauty_lifestyle,2019-02-15
3,-1kNxqvvZsmYDKJ5C-SGGQ,NaN,2019-02-15 02:36:15.050 +0000,my_news_card_viewed,Mort de Kristoff St. John : son ex-femme dévoi...,people_shows,2019-02-15
4,-1kNxqvvZsmYDKJ5C-SGGQ,NaN,2019-02-15 02:36:15.050 +0000,my_news_card_viewed,Mort de Kristoff St. John : son ex-femme dévoi...,people_shows,2019-02-15

In [113]:
# count rows for events
art_perf = stage.groupby(['id', 'date','title', 'category', 'EVENT_NAME']
                ).size().unstack().reset_index().fillna(0)

# combine numbers for card view events
art_perf['card_views']=art_perf.my_news_card_viewed+art_perf.top_news_card_viewed

In [121]:
#create dataframe formatted for article_performance table
article_performance = art_perf.drop(['my_news_card_viewed', 'top_news_card_viewed'], axis=1).rename(columns={"article_viewed": "article_views", "id":"article_id"})

# reoder columns as per requirement
article_performance = article_performance[['article_id', 'date', 'title', 'category', 'card_views', 'article_views']]

In [124]:
article_performance.head()

EVENT_NAME,article_id,date,title,category,card_views,article_views
0,-1e_PWmoy-tnoBrgcDA2-A,2019-02-15,"Aktorzy, którzy zginęli na planie filmowym i p...",fashion_beauty_lifestyle,3.0,0.0
1,-1kNxqvvZsmYDKJ5C-SGGQ,2019-02-15,Mort de Kristoff St. John : son ex-femme dévoi...,people_shows,18.0,0.0
2,-36YHd9KZ1RUVBfCXkvITg,2019-02-15,This Crazy-Affordable Skin Care Brand Gave Me ...,fashion_beauty_lifestyle,9.0,0.0
3,-3RsLiL0PwPUeEwwrEbIMw,2019-02-15,"Lazio, ti è andata pure bene! Banega sontuoso:...",sports,0.0,3.0
4,-72o6DS38oeYSCfz5I5I7Q,2019-02-15,"Zurigo-Napoli, scontri tra ultras nel pre-part...",sports,3.0,0.0

In [140]:
# count rows for events
usr_perf = stage.groupby(['id', 'date', 'EVENT_NAME']
                ).size().unstack().reset_index().fillna(0)

# combine numbers for card view events
#art_perf['card_views']=art_perf.my_news_card_viewed+art_perf.top_news_card_viewed

In [144]:
stage.groupby(['ID','EVENT_NAME']).size()

ID                                    EVENT_NAME
15906afb-e954-4903-9e8a-e6eb054663cc  top_news_card_viewed    3
2C5WI-kOcYNiAfbYDZQHuA                my_news_card_viewed     3
3a378c7b-4f29-43ac-83fc-7130da2387b6  top_news_card_viewed    3
8QwxuqtdKXL8HuE4r4p1zA                my_news_card_viewed     3
B1NrEDY2lIJIAKpFnn9WCA                my_news_card_viewed     3
MXgBH_6JOxJTZZHIk1P1AQ                my_news_card_viewed     3
O5QiZ_8bpyFBQyENLx3aLQ                my_news_card_viewed     6
P1eO-uqJufuVpn_Yaf3f2Q                my_news_card_viewed     3
VrCHOHx5WSjVlbEH_Ni42A                my_news_card_viewed     3
a2493f01-3e87-4e33-ae10-06b7a9af719e  top_news_card_viewed    3
aT-oJJB_0yoroxHjp8EtTA                my_news_card_viewed     3
cW5cwf9ylzeVcOzwRxopAA                my_news_card_viewed     3
e8gZ5BSbEKm9z2ikrT3Jcg                my_news_card_viewed     3
f6Bj0xcTs7wl3l6aEJiKxw                my_news_card_viewed     3
ovTWEd7tFUY7m-go6mUcrw                my_news_card_viewed     3
xM3z-JFqW20qD_zWW1e4GA                my_news_card_viewed     3
dtype: int64

In [146]:
stage[['ID','EVENT_NAME']][~stage.ID.isna()]

                                         ID            EVENT_NAME
27689                aT-oJJB_0yoroxHjp8EtTA   my_news_card_viewed
27694  3a378c7b-4f29-43ac-83fc-7130da2387b6  top_news_card_viewed
27724                xM3z-JFqW20qD_zWW1e4GA   my_news_card_viewed
27810                f6Bj0xcTs7wl3l6aEJiKxw   my_news_card_viewed
27824                8QwxuqtdKXL8HuE4r4p1zA   my_news_card_viewed
27845                O5QiZ_8bpyFBQyENLx3aLQ   my_news_card_viewed
27927                e8gZ5BSbEKm9z2ikrT3Jcg   my_news_card_viewed
27976                ovTWEd7tFUY7m-go6mUcrw   my_news_card_viewed
27977                O5QiZ_8bpyFBQyENLx3aLQ   my_news_card_viewed
27985                2C5WI-kOcYNiAfbYDZQHuA   my_news_card_viewed
28005                VrCHOHx5WSjVlbEH_Ni42A   my_news_card_viewed
28019                MXgBH_6JOxJTZZHIk1P1AQ   my_news_card_viewed
28033                P1eO-uqJufuVpn_Yaf3f2Q   my_news_card_viewed
28035                B1NrEDY2lIJIAKpFnn9WCA   my_news_card_viewed
28054  a2493f01-3e87-4e33-ae10-06b7a9af719e  top_news_card_viewed
28071                cW5cwf9ylzeVcOzwRxopAA   my_news_card_viewed
28101  15906afb-e954-4903-9e8a-e6eb054663cc  top_news_card_viewed
28171                aT-oJJB_0yoroxHjp8EtTA   my_news_card_viewed
28176  3a378c7b-4f29-43ac-83fc-7130da2387b6  top_news_card_viewed
28206                xM3z-JFqW20qD_zWW1e4GA   my_news_card_viewed
28292                f6Bj0xcTs7wl3l6aEJiKxw   my_news_card_viewed
28306                8QwxuqtdKXL8HuE4r4p1zA   my_news_card_viewed
28327                O5QiZ_8bpyFBQyENLx3aLQ   my_news_card_viewed
28409                e8gZ5BSbEKm9z2ikrT3Jcg   my_news_card_viewed
28458                ovTWEd7tFUY7m-go6mUcrw   my_news_card_viewed
28459                O5QiZ_8bpyFBQyENLx3aLQ   my_news_card_viewed
28467                2C5WI-kOcYNiAfbYDZQHuA   my_news_card_viewed
28487                VrCHOHx5WSjVlbEH_Ni42A   my_news_card_viewed
28501                MXgBH_6JOxJTZZHIk1P1AQ   my_news_card_viewed
28515                P1eO-uqJufuVpn_Yaf3f2Q   my_news_card_viewed
28517                B1NrEDY2lIJIAKpFnn9WCA   my_news_card_viewed
28536  a2493f01-3e87-4e33-ae10-06b7a9af719e  top_news_card_viewed
28553                cW5cwf9ylzeVcOzwRxopAA   my_news_card_viewed
28583  15906afb-e954-4903-9e8a-e6eb054663cc  top_news_card_viewed
28653                aT-oJJB_0yoroxHjp8EtTA   my_news_card_viewed
28658  3a378c7b-4f29-43ac-83fc-7130da2387b6  top_news_card_viewed
28688                xM3z-JFqW20qD_zWW1e4GA   my_news_card_viewed
28774                f6Bj0xcTs7wl3l6aEJiKxw   my_news_card_viewed
28788                8QwxuqtdKXL8HuE4r4p1zA   my_news_card_viewed
28809                O5QiZ_8bpyFBQyENLx3aLQ   my_news_card_viewed
28891                e8gZ5BSbEKm9z2ikrT3Jcg   my_news_card_viewed
28940                ovTWEd7tFUY7m-go6mUcrw   my_news_card_viewed
28941                O5QiZ_8bpyFBQyENLx3aLQ   my_news_card_viewed
28949                2C5WI-kOcYNiAfbYDZQHuA   my_news_card_viewed
28969                VrCHOHx5WSjVlbEH_Ni42A   my_news_card_viewed
28983                MXgBH_6JOxJTZZHIk1P1AQ   my_news_card_viewed
28997                P1eO-uqJufuVpn_Yaf3f2Q   my_news_card_viewed
28999                B1NrEDY2lIJIAKpFnn9WCA   my_news_card_viewed
29018  a2493f01-3e87-4e33-ae10-06b7a9af719e  top_news_card_viewed
29035                cW5cwf9ylzeVcOzwRxopAA   my_news_card_viewed
29065  15906afb-e954-4903-9e8a-e6eb054663cc  top_news_card_viewed

In [117]:
article_performance.columns

Index(['article_id', 'date', 'title', 'category', 'article_views',
       'card_views'],
      dtype='object', name='EVENT_NAME')

In [103]:
#complete_df.ID.unique()
complete_df.groupby(['ID']).size()

ID
15906afb-e954-4903-9e8a-e6eb054663cc    3
2C5WI-kOcYNiAfbYDZQHuA                  3
3a378c7b-4f29-43ac-83fc-7130da2387b6    3
8QwxuqtdKXL8HuE4r4p1zA                  3
B1NrEDY2lIJIAKpFnn9WCA                  3
MXgBH_6JOxJTZZHIk1P1AQ                  3
O5QiZ_8bpyFBQyENLx3aLQ                  6
P1eO-uqJufuVpn_Yaf3f2Q                  3
VrCHOHx5WSjVlbEH_Ni42A                  3
a2493f01-3e87-4e33-ae10-06b7a9af719e    3
aT-oJJB_0yoroxHjp8EtTA                  3
cW5cwf9ylzeVcOzwRxopAA                  3
e8gZ5BSbEKm9z2ikrT3Jcg                  3
f6Bj0xcTs7wl3l6aEJiKxw                  3
ovTWEd7tFUY7m-go6mUcrw                  3
xM3z-JFqW20qD_zWW1e4GA                  3
dtype: int64